<template>
  <PageShell title="货物移动" tcode="MIGO"><el-card><el-radio-group v-model="form.bwart"><el-radio-button value="101">101 收货</el-radio-button><el-radio-button value="201">201 成本中心发料</el-radio-button><el-radio-button value="311">311 库存转储</el-radio-button></el-radio-group>
    <div v-if="form.bwart==='101'" class="ref-bar"><el-input v-model="form.refNo" placeholder="采购订单号" /><el-button type="primary" @click="loadPo">加载开放项目</el-button></div>
    <el-form v-if="form.bwart==='201'" inline class="ref-bar"><el-form-item label="成本中心"><el-select v-model="form.items[0].kostl"><el-option v-for="x in centers" :key="x.kostl" :label="`${x.kostl} ${x.name}`" :value="x.kostl" /></el-select></el-form-item></el-form>
    <el-table :data="form.items" border><el-table-column label="物料"><template #default="{row}"><el-input v-model="row.matnr" /></template></el-table-column><el-table-column label="工厂"><template #default="{row}"><el-input v-model="row.werks" /></template></el-table-column><el-table-column label="库存地点"><template #default="{row}"><el-input v-model="row.lgort" /></template></el-table-column><el-table-column v-if="form.bwart==='311'" label="目标库存地点"><template #default="{row}"><el-input v-model="row.toLgort" /></template></el-table-column><el-table-column label="数量"><template #default="{row}"><el-input-number v-model="row.qty" :min="0.001" /></template></el-table-column><el-table-column label="操作"><template #default="{ $index }"><el-button link @click="form.items.splice($index,1)">删除</el-button></template></el-table-column></el-table><el-button class="add-line" @click="add">添加行</el-button><el-button type="primary" @click="post">过账</el-button></el-card>
    <el-dialog v-model="resultVisible" title="物料凭证过账结果"><el-result icon="success" title="过账成功" :sub-title="`物料凭证 ${result?.mblnr || result?.materialDocument} / FI ${result?.fiBelnr || '-'}`" /></el-dialog>
  </PageShell>
</template>
<script setup>
import { onMounted, reactive, ref, watch } from 'vue'; import PageShell from '../../components/PageShell.vue'; import { mmApi } from '../../api'; import { coApi } from '../../api/co'; import { ElMessage } from 'element-plus'
const form=reactive({bwart:'101',refType:'PO',refNo:'',items:[]}),centers=ref([]),result=ref(null),resultVisible=ref(false);function add(){form.items.push({matnr:'M1001',werks:'1000',lgort:'0001',toLgort:'0002',qty:1})};async function loadPo(){const po=await mmApi.po(form.refNo);form.items=(po.items||[]).filter(x=>(x.menge||0)-(x.deliveredQty||0)>0).map(x=>({matnr:x.matnr,werks:x.werks||'1000',lgort:x.lgort||'0001',ebelp:x.ebelp,qty:(x.menge||0)-(x.deliveredQty||0)}));ElMessage.success('已加载开放项目')};async function post(){result.value=await mmApi.migo(form);resultVisible.value=true};watch(()=>form.bwart,()=>{form.items=[];add()});onMounted(async()=>{add();centers.value=await coApi.centers()})
</script>
