<template>
  <PageShell title="采购申请" tcode="ME51N"><template #actions><el-button type="primary" @click="visible=true">创建采购申请</el-button></template>
    <el-card><el-table :data="rows" border stripe><el-table-column prop="banfn" label="申请号" /><el-table-column prop="requester" label="申请人" /><el-table-column prop="werks" label="工厂" /><el-table-column prop="status" label="状态" /><el-table-column prop="totalAmount" label="总金额" /><el-table-column label="操作"><template #default="{row}"><el-button link :disabled="row.status==='ORDERED'" @click="release(row)">释放</el-button><el-button link @click="detail=row">明细</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="visible" title="创建采购申请" width="760px"><el-form :model="form" inline><el-form-item label="申请人"><el-input v-model="form.requester" /></el-form-item><el-form-item label="工厂"><el-input v-model="form.werks" /></el-form-item></el-form><el-table :data="form.items" border><el-table-column label="物料"><template #default="{row}"><el-input v-model="row.matnr" /></template></el-table-column><el-table-column label="数量"><template #default="{row}"><el-input-number v-model="row.menge" :min="1" /></template></el-table-column><el-table-column label="价格"><template #default="{row}"><el-input-number v-model="row.netpr" :min="0" /></template></el-table-column><el-table-column label="工厂"><template #default="{row}"><el-input v-model="row.werks" /></template></el-table-column><el-table-column label="操作"><template #default="{ $index }"><el-button link @click="form.items.splice($index,1)">删除</el-button></template></el-table-column></el-table><el-button class="add-line" @click="add">添加行</el-button><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">提交</el-button></template></el-dialog>
    <el-drawer v-model="detail" title="采购申请明细" size="55%"><pre>{{ JSON.stringify(detail, null, 2) }}</pre></el-drawer>
  </PageShell>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import PageShell from '../../components/PageShell.vue'; import { mmApi } from '../../api'; import { ElMessage } from 'element-plus'
const rows=ref([]),visible=ref(false),detail=ref(null),form=reactive({requester:'',bukrs:'1000',werks:'1000',items:[]});function add(){form.items.push({matnr:'M1001',menge:1,netpr:45,werks:form.werks,lgort:'0001'})};async function load(){rows.value=await mmApi.prs()};async function save(){await mmApi.createPr(form);visible.value=false;form.items=[];load()};async function release(row){await mmApi.releasePr(row.banfn);ElMessage.success('已释放');load()};onMounted(()=>{add();load()})
</script>
